TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 5.00
  min_vel_x: 0.08

  max_vel_theta:  1.0
  min_in_place_vel_theta: 1.0

  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_theta: 1.0

# Differential-drive robot configuration
  holonomic_robot: false
